apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-test
  namespace: dev-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-accelerator
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/emosher/python-test.git
      ref:
        branch: emosher
  serviceClaims:
  - name: psql
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: python-uber

